### ISSUE TITLE
withJvmMetrics does not work

### ISSUE THREAD

**Issue by damianbl** [azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#1]
The reporter works perfectly for me except JvmMetrics.
When I set withJvmMetrics option I get the following error:

```java.lang.NoSuchMethodError: com.codahale.metrics.JmxAttributeGauge.<init>(Ljavax/management/MBeanServerConnection;Ljavax/management/ObjectName;Ljava/lang/String;)V```

I assume it is probably problem with metrics version but I have exactly the same version as you defined in the library. 
So the question is do you also face that error or is it something on my side?

**Comment by azagniotov** [comment]
Hmmmm... @damianbl Thanks for reporting this... 
**Just as a sanity check**: maybe something loads a different version of that class at runtime? In other words, maybe there is an older or newer version of `com.codahale.metrics.JmxAttributeGauge` class floating around? Perhaps there is another version of metrics on the classpath?

I found that other people have been raising questions about the same issue in the past:
https://github.com/dropwizard/metrics/issues/769
https://github.com/dropwizard/metrics/issues/916

Let me know if this helped

**Comment by damianbl** [comment]
Hi, thanks for you answer. Yes, I've already fixed it by fixing by SBT config. Somehow the older version of metrics-core was used then the one I defined.
