### ISSUE TITLE
Artifact missing on maven central

### ISSUE THREAD

**Issue by MarkusKramer** [azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#12]
I would like to use this reporter, but couldn't find the artifact on maven central. Would be great to put it there for ease of use.

**Comment by azagniotov** [comment]
Hello, please refer to: 
https://github.com/azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#dependencies

**Comment by MarkusKramer** [comment]
The desired information is not there

**Comment by azagniotov** [comment]
I am sorry if this is not clear enough, but the following section describes how to include the library as a dependency in your project using Gradle. The `dropwizard-metrics-cloudwatch` is the artifact ID
```
dependencies { 
    compile("io.github.azagniotov:dropwizard-metrics-cloudwatch:1.0.7")
}
```

I will clarify the docs
