### ISSUE TITLE
Send initial zero value

### ISSUE THREAD

**Issue by zersetz-end** [azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#13]
Hey Alexander,

similar to issue #8 I'd like to propose to send a zero value for metrics that haven't been processed before. The reason for this is that I'd like to create a dashboard based on metrics that ideally never have a value greater zero (e.g. a counter for a "this shouldn't happen" exception) but I still want to save some money and not send a zero on every interval.

Let me know what you think and how I might help. Thanks.

Dimitri

**Comment by azagniotov** [comment]
Thanks for that. Feel free to issue a PR similar to PR https://github.com/azagniotov/codahale-aggregated-metrics-cloudwatch-reporter/pull/9
