### ISSUE TITLE
Add the ability to define Dimensions by metric

### ISSUE THREAD

**Issue by davidgodzsak** [azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#19]
In one MetricRegistry there might be multiple metrics, with different data. It would be nice to parse their name and make dimensions from them:

```
String nameAndDimensions = "Name:dim1=val1,dim2=val2";

metricRegistry.meter.update(nameAndDimensions).mark(value);
```

Use case: I am measuring response times of my REST API endpoints, and want to have metrics for each one of them. I could make something like:

```
...

String url = request.url()
String response = response.status().toString();
metricRegistry.meter("Endpoint:url="+url+",status="+status).mark(responseTime);
```

This way I'd get metrics with dimensions on status and url.

**Comment by jebl01** [comment]
this sounds a lot like how [coursera](https://github.com/coursera/metrics-datadog) does the *Datadog* tagging... they also have a *metric name builder* to make it easy to add *tags* to a metric...
