### ISSUE TITLE
Add an working example runtime

### ISSUE THREAD

**Issue by gabrielerzinger** [azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#25]
Hi, first of all thanks for the work, I've been searching for a codahale metrics cloudwatch reporter and found yours with the best documentation amongst others. 

Even though, I wish to ask if there is any working example of how to use it? I **must be missing something obvious**, but I cant figure out how I do configure connection with AWS Cloudwatch just like i used to do with graphite reporter.

I've used the Readme example configuration... If there is no example, I would be happy to open a PR as soon as i understand how to do so.

Also, I cant use the option _withJvmMetrics_ as it throws `ClassNotFoundException: com.codahale.metrics.jvm.ClassLoadingGaugeSet`

**Comment by gabrielerzinger** [comment]
Amazon gets configured by default once you set application.properties accordingly. Also, the exception was due to transitive dependency on codahale  conflicts with my codahale core import. Just had to exclude that and voila.

**Comment by azagniotov** [comment]
I am glad you got this resolved, @gabrielerzinger . Thanks for the kind words!
