### ISSUE TITLE
JVMMetrics: A metric named jvm.buffers.direct.count already exists 

### ISSUE THREAD

**Issue by irineuruiz** [azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#38]
Hi,

We were adding CloudWatchReporter 2.0.5 to our Dropwizard application.

However, if we call the .withJvmMetrics() method, the application does not start and gives the error

java.lang.IllegalArgumentException: A metric named jvm.buffers.direct.count already exists
at com.codahale.metrics.MetricRegistry.register (MetricRegistry.java:156)
at com.codahale.metrics.MetricRegistry.registerAll (MetricRegistry.java/1675)
at com.codahale.metrics.MetricRegistry.register (MetricRegistry.java:150)
at io.github.azagniotov.metrics.reporter.cloudwatch.CloudWatchReporter $ Builder.build (CloudWatchReporter.java:778)

From what I've seen, this is because the Application class in the run(String ... arguments) method executes bootstrap.registerMetrics();

And the Bootstrap class in turn already registers

        getMetricRegistry (). register ("jvm.attribute", new JvmAttributeGaugeSet ());
        getMetricRegistry (). register ("jvm.buffers", new BufferPoolMetricSet (ManagementFactory
                                                                               .getPlatformMBeanServer ()));
        getMetricRegistry (). register ("jvm.classloader", new ClassLoadingGaugeSet ());
        getMetricRegistry (). register ("jvm.filedescriptor", new FileDescriptorRatioGauge ());
        getMetricRegistry (). register ("jvm.gc", new GarbageCollectorMetricSet ());
        getMetricRegistry (). register ("jvm.memory", new MemoryUsageGaugeSet ());
        getMetricRegistry (). register ("jvm.threads", new ThreadStatesGaugeSet ());

Are we doing something wrong?

**Comment by azagniotov** [comment]
It looks like dropwizard already registers JVM metrics for you, can you not call the “ withJvmMetrics()”? 

The MetricRegistry is a singleton, so when you are trying to register the same metric twice from two different locations, you get exception.
