### ISSUE TITLE
Upgrade from 2.0.5 to 2.0.7 does not work like expected

### ISSUE THREAD

**Issue by irineuruiz** [azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#39]
Hi,

I tried to upgrade from 2.0.5 to 2.0.7, which should work, I imagine ...

But our code doesn't compile anymore

The software.amazon.awssdk.services.cloudwatch.CloudWatchAsyncClient type cannot be resolved. It is indirectly referenced from necessary .class files

This is the error of the code below

`final CloudWatchAsyncClient amazonCloudWatchAsync = CloudWatchAsyncClient
                .builder()
                .region(this.getAWSRegion())
                .build();`

**Comment by azagniotov** [comment]
Hi @irineuruiz ,
The JARs on Maven Central are skinny jars. Which means, you need to have the following in your project build tool (if you are using Gradle):
```
   implementation("io.dropwizard.metrics:metrics-core:4.1.8")
    implementation("io.dropwizard.metrics:metrics-jvm:4.1.8")
    implementation("software.amazon.awssdk:cloudwatch:2.13.8")
    implementation("org.slf4j:slf4j-api:1.7.30")
```
That said, I can look into publishing also the fat/uber JAR artifact

**Comment by azagniotov** [comment]
Which brings a question: if you have been using a skinny JAR v2.0.5 before, everything worked fine for you?

**Comment by irineuruiz** [comment]
> Which brings a question: if you have been using a skinny JAR v2.0.5 before, everything worked fine for you?

Hi @azagniotov 

We use Maven instead of Gradle.
As far as I can tell, version 2.0.5 in the repository is not skinny while version 2.0.7 you uploaded is.

		<dependency>
    		<groupId>io.github.azagniotov</groupId>
    		<artifactId>dropwizard-metrics-cloudwatch</artifactId>
    		<version>2.0.5</version>
		</dependency>		


		<dependency>
    		<groupId>io.github.azagniotov</groupId>
    		<artifactId>dropwizard-metrics-cloudwatch</artifactId>
    		<version>2.0.7</version>
		</dependency>	

https://mvnrepository.com/artifact/io.github.azagniotov/dropwizard-metrics-cloudwatch	


It might be good to put the fat version there to keep the default, as changing a minor version shouldn't break anything in theory ...

**Comment by azagniotov** [comment]
@irineuruiz hello.

Both versions are skinny, you can have a look at the actual JAR archive contents:

https://repo1.maven.org/maven2/io/github/azagniotov/dropwizard-metrics-cloudwatch/2.0.5/
VS
https://repo1.maven.org/maven2/io/github/azagniotov/dropwizard-metrics-cloudwatch/2.0.7/

(btw, the `mvnrepository.com` is just a mirror of Maven Central, the official Maven Search is: `https://search.maven.org/`)

That said, I do see differences in POM files of `2.0.5` and `2.0.7` versions. The dependencies in the `2.0.5` POM have a `compile` scope:
```
<dependency>
<groupId>io.dropwizard.metrics</groupId>
<artifactId>metrics-core</artifactId>
<version>4.0.7</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>io.dropwizard.metrics</groupId>
<artifactId>metrics-jvm</artifactId>
<version>4.0.7</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>software.amazon.awssdk</groupId>
<artifactId>cloudwatch</artifactId>
<version>2.11.3</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-api</artifactId>
<version>1.7.29</version>
<scope>compile</scope>
</dependency>
```
while dependencies in the `2.0.7` POM have a `runtime` scope:
```

<dependency>
<groupId>io.dropwizard.metrics</groupId>
<artifactId>metrics-core</artifactId>
<version>4.1.8</version>
<scope>runtime</scope>
</dependency>
<dependency>
<groupId>io.dropwizard.metrics</groupId>
<artifactId>metrics-jvm</artifactId>
<version>4.1.8</version>
<scope>runtime</scope>
</dependency>
<dependency>
<groupId>software.amazon.awssdk</groupId>
<artifactId>cloudwatch</artifactId>
<version>2.13.8</version>
<scope>runtime</scope>
</dependency>
<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-api</artifactId>
<version>1.7.30</version>
<scope>runtime</scope>
</dependency>
```

I think this maybe the issue that is causing problem for you. 

I will change the `build.gradle` so that when I stage & publish the JAR artifacts, the accompanied generated POM will have a `compile` scope on the dependencies. Please allow me a day for this

**Comment by irineuruiz** [comment]
> @irineuruiz hello.
> 
> Both versions are skinny, you can have a look at the actual JAR archive contents:
> 
> https://repo1.maven.org/maven2/io/github/azagniotov/dropwizard-metrics-cloudwatch/2.0.5/
> VS
> https://repo1.maven.org/maven2/io/github/azagniotov/dropwizard-metrics-cloudwatch/2.0.7/
> 
> (btw, the `mvnrepository.com` is just a mirror of Maven Central, the official Maven Search is: `https://search.maven.org/`)
> 
> That said, I do see differences in POM files of `2.0.5` and `2.0.7` versions. The dependencies in the `2.0.5` POM have a `compile` scope:
> 
> ```
> <dependency>
> <groupId>io.dropwizard.metrics</groupId>
> <artifactId>metrics-core</artifactId>
> <version>4.0.7</version>
> <scope>compile</scope>
> </dependency>
> <dependency>
> <groupId>io.dropwizard.metrics</groupId>
> <artifactId>metrics-jvm</artifactId>
> <version>4.0.7</version>
> <scope>compile</scope>
> </dependency>
> <dependency>
> <groupId>software.amazon.awssdk</groupId>
> <artifactId>cloudwatch</artifactId>
> <version>2.11.3</version>
> <scope>compile</scope>
> </dependency>
> <dependency>
> <groupId>org.slf4j</groupId>
> <artifactId>slf4j-api</artifactId>
> <version>1.7.29</version>
> <scope>compile</scope>
> </dependency>
> ```
> 
> while dependencies in the `2.0.7` POM have a `runtime` scope:
> 
> ```
> 
> <dependency>
> <groupId>io.dropwizard.metrics</groupId>
> <artifactId>metrics-core</artifactId>
> <version>4.1.8</version>
> <scope>runtime</scope>
> </dependency>
> <dependency>
> <groupId>io.dropwizard.metrics</groupId>
> <artifactId>metrics-jvm</artifactId>
> <version>4.1.8</version>
> <scope>runtime</scope>
> </dependency>
> <dependency>
> <groupId>software.amazon.awssdk</groupId>
> <artifactId>cloudwatch</artifactId>
> <version>2.13.8</version>
> <scope>runtime</scope>
> </dependency>
> <dependency>
> <groupId>org.slf4j</groupId>
> <artifactId>slf4j-api</artifactId>
> <version>1.7.30</version>
> <scope>runtime</scope>
> </dependency>
> ```
> 
> I think this maybe the issue that is causing problem for you.
> 
> I will change the `build.gradle` so that when I stage & publish the JAR artifacts, the accompanied generated POM will have a `compile` scope on the dependencies. Please allow me a day for this

I also noticed this. apparently the difference is that in the new version it has a runtime scope instead of compile

Thank you.

**Comment by azagniotov** [comment]
@irineuruiz I just staged for release a newer version `v2.0.8` which contains POM with `compile` scope. I hope this was the culprit. Feel free to re-open this issue if the problem is not resoled
